pre-commit config & github linter CI
zchunk/zchunk pull request #63
Opened 2022-01-09 12:23 UTC by wolfv

This adds a `.pre-commit-config.yml` config and a github actions based linter step. 

Currently it only checks for end of file newlines (and auto-corrects them when running locally with `pre-commit run --all`.

There are a couple other nice linter steps supported with `pre-commit`. A list of pre-provided hooks is here: https://github.com/pre-commit/pre-commit-hooks

One I find personally quite useful is `clang-format`. 
That could be configured like so:

```
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: master
    hooks:
    -   id: clang-format
        args: [--style=file]
```

And would require an `.clang-format` in the root of the repo (e.g. https://github.com/mamba-org/mamba/blob/master/.clang-format). We'd need to figure out the proper values to match the current style of zchunk.

2022-01-09 20:39 UTC, jdieter requested changes
Since this only needs to run under Ubuntu, I would prefer that we're not using mamba and conda-forge for this.  Can we just run a `pip install pre-commit` to install these under Ubuntu and then run the linter?

2022-01-09 20:46 UTC, wolfv commented
Yes, sure. A useful thing about using mamba/conda-forge is that it allows you to specify an exact version of clang-format (which sometimes changes slightly how it ends up formatting the source code) if you don't want to use clang format at this point it doesn't matter much.

2022-01-09 20:50 UTC, jdieter commented
> Yes, sure. A useful thing about using mamba/conda-forge is that it allows you to specify an exact version of clang-format (which sometimes changes slightly how it ends up formatting the source code) if you don't want to use clang format at this point it doesn't matter much.

I think I would be interested in eventually using clang-format, but, if it's installed through `pip`, we can pin the version there, right?

2022-01-10 07:00 UTC, wolfv commented
Yeah, that works! Although I still don't think that `pip` is the proper way of getting `clang-format` -- but that's a matter of personal taste :)

2022-01-10 21:28 UTC, jdieter commented
This looks great!  Thanks!

2022-01-10 21:28 UTC, merged